abbr --add g "git"
abbr --add gs "git status"
abbr --add gf "git fetch"
abbr --add gp "git pull"
abbr --add gP "git push"
abbr --add gpf "git push --force-with-lease"
abbr --add ga "git add"
abbr --add gc "git commit"
abbr --add gcm "git commit -m"
abbr --add gcam "git commit -am"
abbr --add gt "git stash"
abbr --add gtp "git stash pop"
abbr --add gl "git log --oneline --graph"
abbr --add gb "git branch"
abbr --add gsw "git switch"
abbr --add gw "git worktree"
abbr --add gd "git diff"

abbr --add cz "chezmoi"
abbr --add czapp "chezmoi apply"

abbr --add occ "oc config current-context"
abbr --add ocsw "oc config use-context"

