abbr --add gs "git status"
abbr --add gp "git pull"
abbr --add gP "git push"
abbr --add ga "git add"
abbr --add gc "git commit"
abbr --add gcm "git commit -m"
abbr --add gcam "git commit -am"
abbr --add gt "git stash"
abbr --add gtp "git stash pop"
abbr --add gl "git log --oneline --graph"
abbr --add gsw "git switch"

abbr --add cz "chezmoi"
abbr --add czapp "chezmoi apply"

